- hosts: localhost
  connection: local
  become: true

  vars:
    pkgs:
      - {name: "vimpager", repo: "https://github.com/rkitover/vimpager.git", dest: "/usr/local/src/vimpager", binary: "/usr/local/bin/vimpager"}
      - {name: "sedtris", repo: "https://github.com/jbrubake/sedtris.git", dest: "/usr/local/src/sedtris", binary: "/usr/local/games/sedtris"}

  tasks:
    - name: "Check for {{ item.name }}"
      stat:
        path: "{{ item.binary }}"
      register: pkg_path
      loop: "{{ pkgs }}"

    - name: "Install {{ item.name }} from source"
      # when: "not pkg_path.stat.exists"
      block:
        - name: "Clone {{ item.name }} repo"
          ansible.builtin.git:
            repo: "{{ item.repo }}"
            dest: "{{ item.dest }}"
          # loop: "{{ pkgs }}"
        - name: "Build and install {{ item.name }} from source"
          make:
            chdir: "{{ item.dest }}"
            target: install
      loop: "{{ pkgs }}"
