---
- name: "Check for {{ item.name }}"
  stat:
    path: "{{ item.binary }}"
  register: pkg

- name: "Clone {{ item.name }} repo"
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  when: not pkg.stat.exists
- name: "Build and install {{ item.name }} from source"
  make:
    chdir: "{{ item.dest }}"
    target: install
  when: not pkg.stat.exists
...

