---
- name: "Check for {{ item.name }}"
  stat:
    path: "{{ item.binary }}"
  register: pkg

- block:
  - name: "Clone {{ item.name }} repo"
    ansible.builtin.git:
      repo: "{{ item.repo }}"
      dest: "{{ item.dest }}"
  - name: "Build {{ item.name }}"
    make:
      chdir: "{{ item.dest }}"
      target: all
  - name: "Install {{ item.name }}"
    make:
      chdir: "{{ item.dest }}"
      target: install

  when: not pkg.stat.exists
...

