---

- hosts: localhost

  vars:
    porg:
      name: porg
      repo: https://github.com/alinaresz/porg.git
      dest: /usr/local/src/porg
      binary: /usr/local/bin/porg

  tasks:
  - name: "Check for {{ porg.name }}"
    stat:
      path: "{{ porg.binary }}"
    register: pkg

  - block:
    - name: "Install  {{ porg.name }} dependencies"
      ansible.builtin.package:
        name:
          - gtkmm30-devel
          - python3-html2text
          - gcc-c++
        state: present

    - name: "Clone {{ porg.name }} repo"
      ansible.builtin.git:
        repo: "{{ porg.repo }}"
        dest: "{{ porg.dest }}"
    - name: "Configure {{ porg.name }}"
      command: ./configure
      args:
        chdir: "{{ porg.dest }}"
    - name: "Build {{ porg.name }}"
      make:
        chdir: "{{ porg.dest }}"
        target: all
    # - name: "Install {{ porg.name }}"
      # make:
        # chdir: "{{ porg.dest }}"
        # target: install

    when: not pkg.stat.exists
...

