---

- name: "Check for porg"
  stat:
    path: "/usr/local/bin/porg"
  register: pkg

- block:
  - name: "Install  porg dependencies"
    ansible.builtin.package:
      name:
        - gtkmm30-devel
        - python3-html2text
        - gcc-c++
      state: present

  - name: "Clone porg repo"
    ansible.builtin.git:
      repo: https://github.com/alinaresz/porg.git
      dest: "/usr/local/src/porg"
  - name: "Configure porg"
    ansible.builtin.command: ./configure
    args:
      chdir: "/usr/local/src/porg"
  - name: "Build porg"
    make:
      chdir: "/usr/local/src/porg"
      target: all
  - name: "Install porg"
    ansible.builtin.command:
      argv:
        - porg/porg
        - "-lD"
        - "make install"
      chdir: "/usr/local/src/porg"

  when: not pkg.stat.exists
...

