---
- name: Build workstation
  hosts: localhost

  tasks:
    - include_tasks: "{{ item }}.yaml"
      loop:
        - common-utils
        # - advanced-utils
        - devtools
        - x11-tools
        - x11-advanced-tools
        - email

    - include_tasks: install_porg.yaml

    - include_tasks: "install_{{ item }}.yaml"
      loop:
        - jumpapp
        - tdrop
        - gws
        - binprint
        - vimpager
...

