---

# - import_playbook: build.yaml

- name: Build workstation
  hosts: localhost

  tasks:
    - import_tasks: install_porg.yaml
    - name: Load package info
      include_vars: pkg_vars.yaml
    - import_tasks: build.yaml
    # - import_tasks: common-utils.yaml
    # - import_tasks: advanced-utils.yaml
    # - import_tasks: devtools.yaml
    # - import_tasks: x11-tools.yaml
    # - import_tasks: x11-advanced-tools.yaml
    # - import_tasks: email.yaml
...

